import { Asset } from 'expo-asset';

export const videoDetails = [
    {
        id: "1",
        english_title: "A Cloud of Trash ",
        punjabi_title: "ਕੂੜੇ ਦਾ ਬੱਦਲ",
        url_en: require('@/assets/1.mp4'),
        url_punjabi: require('@/assets/1.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/1.pdf')),
        pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/A_Cloud_of_Trash_Punjabi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/A_Cloud_of_Trash_English.png'),
        thumbnail_punjabi: require('@/assets/thumbnails/punjabi/A_Cloud_of_Trash_Punjabi.png'),
        description: "This is A Cloud of Trash ",
        level: "2"
    },
    {
        id: "2",
        english_title: "A Street or a Zoo ",
        punjabi_title: "ਇੱਕ ਗਲੀ ਜਾਂ ਇੱਕ ਚਿੜੀਆਘਰ?",
        url_en: require('@/assets/1.mp4'),
        url_punjabi: require('@/assets/1.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/1.pdf')),
        pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/A_Street,_or_a_Zoo_Punjabi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/A_Street,_or_a_Zoo_English.png'),
        thumbnail_punjabi: require('@/assets/thumbnails/punjabi/A_Street,_or_a_Zoo_Punjabi.png'),
        description: "This is A Street or a Zoo ",
        level: "2"
    },
    {
        id: "3",
        english_title: "Aaloo Maaloo Kaaloo ",
        punjabi_title: "ਆਲੂ-ਮਾਲੂ-ਕਾਲੂ",
        url_en: require('@/assets/1.mp4'),
        url_punjabi: require('@/assets/1.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/1.pdf')),
        pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Aaloo_Maaloo_Kaaloo_Punjabi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Aaloo_Maaloo_Kaaloo_English.png'),
        thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Aaloo_Maaloo_Kaaloo_Punjabi.png'),
        description: "This is Aaloo Maaloo Kaaloo ",
        level: "2"
    },
    // {
    //     id: "4",
    //     english_title: "Abdul Kalam, A Lesson for my Teacher ",
    //     punjabi_title: "ਮੇਰੇ ਅਧਿਆਪਕ ਲਈ ਇੱਕ ਸਬਕ",
    //     url_en: require('@/assets/videos/english/Abdul_Kalam,_A_Lesson_for_my_Teacher_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Abdul_Kalam,_A_Lesson_for_my_Teacher_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/1.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Abdul_Kalam,_A_Lesson_for_my_Teacher_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Abdul_Kalam,_A_Lesson_for_my_Teacher_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Abdul_Kalam,_A_Lesson_for_my_Teacher_Punjabi.png'),
    //     description: "This is Abdul Kalam, A Lesson for my Teacher ",
    //     level: "4"
    // },
    // {
    //     id: "5",
    //     english_title: "Abdul Kalam, Designing a Fighter Jet ",
    //     punjabi_title: "ਇੱਕ ਲੜਾਕੂ ਜਹਾਜ਼ ਡਿਜ਼ਾ ਈਨ ਕਰਨਾ",
    //     url_en: require('@/assets/videos/english/Abdul_Kalam,_Designing_a_Fighter_Jet_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Abdul_Kalam,_Designing_a_Fighter_Jet_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/1.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Abdul_Kalam,_Designing_a_Fighter_Jet_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Abdul_Kalam,_Designing_a_Fighter_Jet_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Abdul_Kalam,_Designing_a_Fighter_Jet_Punjabi.png'),
    //     description: "This is Abdul Kalam, Designing a Fighter Jet ",
    //     level: "4"
    // },
    // {
    //     id: "6",
    //     english_title: "Abdul Kalam, Failure to Success ",
    //     punjabi_title: "ਅਸਫਲਤਾ ਤੋਂ ਸਫਲਤਾ ਵੱਲ",
    //     url_en: require('@/assets/videos/english/Abdul_Kalam,_Failure_to_Success_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Abdul_Kalam,_Failure_to_Success_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/1.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Abdul_Kalam,_Failure_to_Success_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Abdul_Kalam,_Failure_to_Success_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Abdul_Kalam,_Failure_to_Success_Punjabi.png'),
    //     description: "This is Abdul Kalam, Failure to Success ",
    //     level: "4"
    // },
    // {
    //     id: "7",
    //     english_title: "Abdul Kalam, Missile Man ",
    //     punjabi_title: "ਅਸਫਲਤਾ ਤੋਂ ਸਫਲਤਾ ਵੱਲ",
    //     url_en: require('@/assets/videos/english/Abdul_Kalam,_Missile_Man_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Abdul_Kalam,_Missile_Man_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Abdul_Kalam,_Missile_Man_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Abdul_Kalam,_Missile_Man_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Abdul_Kalam,_Missile_Man_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Abdul_Kalam,_Missile_Man_Punjabi.png'),
    //     description: "This is Abdul Kalam, Missile Man ",
    //     level: "4"
    // },
    // {
    //     id: "8",
    //     english_title: "Abdul Kalam, School Topper ",
    //     punjabi_title: "ਸਕੂਲ ਵਿੱਚ ਅਵੱਲ ਆਉਣ ਵਾਲਾ ਵਿਦਿਆਰਥੀ",
    //     url_en: require('@/assets/videos/english/Abdul_Kalam,_School_Topper_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Abdul_Kalam,_School_Topper_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Abdul_Kalam,_School_Topper_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Abdul_Kalam,_School_Topper_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Abdul_Kalam,_School_Topper_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Abdul_Kalam,_School_Topper_Punjabi.png'),
    //     description: "This is Abdul Kalam, School Topper ",
    //     level: "4"
    // },
    // {
    //     id: "9",
    //     english_title: "Ammus Puppy ",
    //     punjabi_title: "ਅੰਮੂ ਦਾ ਕਤੂਰਾ",
    //     url_en: require('@/assets/videos/english/Ammus_Puppy_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Ammus_Puppy_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/1.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Ammus_Puppy_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Ammus_Puppy_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Ammus_Puppy_Punjabi.png'),
    //     description: "This is Ammus Puppy ",
    //     level: "3"
    // },
    // {
    //     id: "10",
    //     english_title: "Bheema, the Sleepyhead ",
    //     punjabi_title: "ਸੁਸਤ ਭੀਮ",
    //     url_en: require('@/assets/videos/english/Bheema,_the_Sleepyhead_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Bheema,_the_Sleepyhead_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/1.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Bheema,_the_Sleepyhead_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Bheema,_the_Sleepyhead_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Bheema,_the_Sleepyhead_Punjabi.png'),
    //     description: "This is Bheema, the Sleepyhead ",
    //     level: "3"
    // },
    // {
    //     id: "11",
    //     english_title: "Bunty and Bubbly ",
    //     punjabi_title: "ਬੰਟੀ ਅਤੇ ਬਬਲੀ",
    //     url_en: require('@/assets/videos/english/Bunty_and_Bubbly_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Bunty_and_Bubbly_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/1.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Bunty_and_Bubbly_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Bunty_and_Bubbly_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Bunty_and_Bubbly_Punjabi.png'),
    //     description: "This is Bunty and Bubbly ",
    //     level: "1"
    // },
    // {
    //     id: "12",
    //     english_title: "Cheeku & Chikootichoo ",
    //     punjabi_title: "ਚੀਕੂ ਅਤੇ ਚੀਕੂਟੀਚੂ",
    //     url_en: require('@/assets/videos/english/Cheeku_&_Chikootichoo_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Cheeku_&_Chikootichoo_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Cheeku_&_Chikootichoo_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Cheeku_&_Chikootichoo_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Cheeku_&_Chikootichoo_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Cheeku_&_Chikootichoo_Punjabi.png'),
    //     description: "This is Cheeku & Chikootichoo ",
    //     level: "2"
    // },
    // {
    //     id: "13",
    //     english_title: "Cheeku & Lizzy Bizzy ",
    //     punjabi_title: "ਚੀਕੂ ਅਤੇ ਲਿਜ਼ੀ ਬਿਜ਼ੀ",
    //     url_en: require('@/assets/videos/english/Cheeku_&_Lizzy_Bizzy_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Cheeku_&_Lizzy_Bizzy_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Cheeku_&_Lizzy_Bizzy_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Cheeku_&_Lizzy_Bizzy_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Cheeku_&_Lizzy_Bizzy_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Cheeku_&_Lizzy_Bizzy_Punjabi.png'),
    //     description: "This is Cheeku & Lizzy Bizzy ",
    //     level: "2"
    // },
    // {
    //     id: "14",
    //     english_title: "Cheeku & Tooi ",
    //     punjabi_title: "ਚੀਕੂ ਅਤੇ ਟੂਈ",
    //     url_en: require('@/assets/videos/english/Cheeku_&_Tooi_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Cheeku_&_Tooi_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Cheeku_&_Tooi_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Cheeku_&_Tooi_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Cheeku_&_Tooi_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Cheeku_&_Tooi_Punjabi.png'),
    //     description: "This is Cheeku & Tooi ",
    //     level: "2"
    // },
    // {
    //     id: "15",
    //     english_title: "Cricket at the Zoo ",
    //     punjabi_title: "ਚਿੜੀਆਘਰ ਵਿੱਚ ਕ੍ਰਿਕਟ",
    //     url_en: require('@/assets/videos/english/Cricket_at_the_Zoo_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Cricket_at_the_Zoo_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Cricket_at_the_Zoo_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Cricket_at_the_Zoo_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Cricket_at_the_Zoo_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Cricket_at_the_Zoo_Punjabi.png'),
    //     description: "This is Cricket at the Zoo ",
    //     level: "3"
    // },
    // {
    //     id: "16",
    //     english_title: "Didi and the Colourful Treasure ",
    //     punjabi_title: "ਦੀਦੀ ਅਤੇ ਰੰਗੀਨ ਖਜਾਨਾ",
    //     url_en: require('@/assets/videos/english/Didi_and_the_Colourful_Treasure_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Didi_and_the_Colourful_Treasure_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Didi_and_the_Colourful_Treasure_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Didi_and_the_Colourful_Treasure_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Didi_and_the_Colourful_Treasure_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Didi_and_the_Colourful_Treasure_Punjabi.png'),
    //     description: "This is Didi and the Colourful Treasure ",
    //     level: "2"
    // },
    // {
    //     id: "17",
    //     english_title: "Farida Plans a Feast ",
    //     punjabi_title: "ਫਰੀਦਾ ਨੇ ਦਾਵਤ ਦੀ ਯੋਜਨਾ ਬਣਾਈ",
    //     url_en: require('@/assets/videos/english/Farida_Plans_a_Feast_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Farida_Plans_a_Feast_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Farida_Plans_a_Feast_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Farida_Plans_a_Feast_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Farida_Plans_a_Feast_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Farida_Plans_a_Feast_Punjabi.png'),
    //     description: "This is Farida Plans a Feast ",
    //     level: "2"
    // },
    // {
    //     id: "18",
    //     english_title: "Gajapati Kulapati ",
    //     punjabi_title: "ਗਜਪਤੀ ਕੁਲਪਤੀ",
    //     url_en: require('@/assets/videos/english/Gajapati_Kulapati_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Gajapati_Kulapati_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Gajapati_Kulapati_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Gajapati_Kulapati_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Gajapati_Kulapati_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Gajapati_Kulapati_Punjabi.png'),
    //     description: "This is Gajapati Kulapati ",
    //     level: "3"
    // },
    // {
    //     id: "19",
    //     english_title: "Kiran Bedi, Crane Bedi ",
    //     punjabi_title: "ਕਰੇਨ੍ ਬੇਦੀ",
    //     url_en: require('@/assets/videos/english/Kiran_Bedi,_Crane_Bedi_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Kiran_Bedi,_Crane_Bedi_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Kiran_Bedi,_Crane_Bedi_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Kiran_Bedi,_Crane_Bedi_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Kiran_Bedi,_Crane_Bedi_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Kiran_Bedi,_Crane_Bedi_Punjabi.png'),
    //     description: "This is Kiran Bedi, Crane Bedi ",
    //     level: "4"
    // },
    // {
    //     id: "20",
    //     english_title: "Kiran Bedi, How to Lose a Shoe ",
    //     punjabi_title: "ਆਪਣੇ ਜੱ ੁਤੇ ਕਿਵੇਂ ਗਵਾਏ ਜਾਣ",
    //     url_en: require('@/assets/videos/english/Kiran_Bedi,_How_to_Lose_a_Shoe_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Kiran_Bedi,_How_to_Lose_a_Shoe_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Kiran_Bedi,_How_to_Lose_a_Shoe_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Kiran_Bedi,_How_to_Lose_a_Shoe_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Kiran_Bedi,_How_to_Lose_a_Shoe_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Kiran_Bedi,_How_to_Lose_a_Shoe_Punjabi.png'),
    //     description: "This is Kiran Bedi, How to Lose a Shoe ",
    //     level: "4"
    // },
    // {
    //     id: "21",
    //     english_title: "Kiran Bedi, Thank you Mr. Secretary ",
    //     punjabi_title: "ਧੰਨਵਾਦ ਸ਼੍ਰੀਮਾਨ ਸੈਕਟਰੀ",
    //     url_en: require('@/assets/videos/english/Kiran_Bedi,_Thank_you_Mr._Secretary_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Kiran_Bedi,_Thank_you_Mr._Secretary_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Kiran_Bedi,_Thank_you_Mr._Secretary_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Kiran_Bedi,_Thank_you_Mr._Secretary_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Kiran_Bedi,_Thank_you_Mr._Secretary_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Kiran_Bedi,_Thank_you_Mr._Secretary_Punjabi.png'),
    //     description: "This is Kiran Bedi, Thank you Mr. Secretary ",
    //     level: "4"
    // },
    // {
    //     id: "22",
    //     english_title: "Kiran Bedi, Tihar Jail ",
    //     punjabi_title: "ਤਿਹਾੜ ਜੇਲ੍ਹ",
    //     url_en: require('@/assets/videos/english/Kiran_Bedi,_Tihar_Jail_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Kiran_Bedi,_Tihar_Jail_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Kiran_Bedi,_Tihar_Jail_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Kiran_Bedi,_Tihar_Jail_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Kiran_Bedi,_Tihar_Jail_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Kiran_Bedi,_Tihar_Jail_Punjabi.png'),
    //     description: "This is Kiran Bedi, Tihar Jail ",
    //     level: "4"
    // },
    // {
    //     id: "23",
    //     english_title: "Lost and Found ",
    //     punjabi_title: "ਗੁੰਮਿਆ ਅਤੇ ਲੱਭਿਆ",
    //     url_en: require('@/assets/videos/english/Lost_and_Found_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Lost_and_Found_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Lost_and_Found_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Lost_and_Found_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Lost_and_Found_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Lost_and_Found_Punjabi.png'),
    //     description: "This is Lost and Found ",
    //     level: "2"
    // },
    // {
    //     id: "24",
    //     english_title: "Mahatma Gandhi, The Salt March ",
    //     punjabi_title: "ਮਹਾਤਮਾ ਗਾਂਧੀ, ਡਾਂਡੀ ਮਾਰਚ",
    //     url_en: require('@/assets/videos/english/Mahatma_Gandhi,_The_Salt_March_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Mahatma_Gandhi,_The_Salt_March_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Mahatma_Gandhi,_The_Salt_March_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Mahatma_Gandhi,_The_Salt_March_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Mahatma_Gandhi,_The_Salt_March_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Mahatma_Gandhi,_The_Salt_March_Punjabi.png'),
    //     description: "This is Mahatma Gandhi, The Salt March ",
    //     level: "4"
    // },
    // {
    //     id: "25",
    //     english_title: "My Car ",
    //     punjabi_title: "ਮੇਰੀ ਕਾਰ",
    //     url_en: require('@/assets/videos/english/My_Car_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/My_Car_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/My_Car_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/My_Car_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/My_Car_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/My_Car_Punjabi.png'),
    //     description: "This is My Car ",
    //     level: "2"
    // },
    // {
    //     id: "26",
    //     english_title: "No Smiles Today ",
    //     punjabi_title: "ਅੱਜ ਕੋਈ ਮੁਸਕਰਾਹਟ ਨਹੀਂ",
    //     url_en: require('@/assets/videos/english/No_Smiles_Today_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/No_Smiles_Today_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/No_Smiles_Today_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/No_Smiles_Today_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/No_Smiles_Today_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/No_Smiles_Today_Punjabi.png'),
    //     description: "This is No Smiles Today ",
    //     level: "3"
    // },
    // {
    //     id: "27",
    //     english_title: "Pishi Caught in a Storm ",
    //     punjabi_title: "ਪੀਸ਼ੀ ਤੂਫ਼ਾਨ ਵਿੱਚ ਫਸਿਆ",
    //     url_en: require('@/assets/videos/english/Pishi_Caught_in_a_Storm_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Pishi_Caught_in_a_Storm_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Pishi_Caught_in_a_Storm_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Pishi_Caught_in_a_Storm_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Pishi_Caught_in_a_Storm_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Pishi_Caught_in_a_Storm_Punjabi.png'),
    //     description: "This is Pishi Caught in a Storm ",
    //     level: "3"
    // },
    // {
    //     id: "28",
    //     english_title: "Punyakoti the Cow ",
    //     punjabi_title: "ਪੰ ੁਨਿਆਕੋਟੀ ਗਾਂ",
    //     url_en: require('@/assets/videos/english/Punyakoti_the_Cow_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Punyakoti_the_Cow_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Punyakoti_the_Cow_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Punyakoti_the_Cow_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Punyakoti,_the_Cow_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Punyakoti,_the_Cow_Punjabi.png'),
    //     description: "This is Punyakoti the Cow ",
    //     level: "4"
    // },
    // {
    //     id: "29",
    //     english_title: "Rain Rain ",
    //     punjabi_title: "ਮੀਂਹ, ਮੀਂਹ",
    //     url_en: require('@/assets/videos/english/Rain_Rain_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Rain_Rain_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Rain_Rain_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Rain_Rain_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Rain_Rain_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Rain_Rain_Punjabi.png'),
    //     description: "This is Rain Rain ",
    //     level: "2"
    // },
    // {
    //     id: "30",
    //     english_title: "Ranis First Day at School ",
    //     punjabi_title: "ਰਾਣੀ ਦਾ ਸਕੂਲ ਵਿੱਚ ਪਹਿਲਾ ਦਿਨ",
    //     url_en: require('@/assets/videos/english/Ranis_First_Day_at_School_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Ranis_First_Day_at_School_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Ranis_First_Day_at_School_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Ranis_First_Day_at_School_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Ranis_First_Day_at_School_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Ranis_First_Day_at_School_Punjabi.png'),
    //     description: "This is Ranis First Day at School ",
    //     level: "2"
    // },
    // {
    //     id: "31",
    //     english_title: "Rosa Goes to the City ",
    //     punjabi_title: "ਰੋਜ਼ਾ ਸ਼ਹਿਰ ਜਾਂਦੀ ਹੈ",
    //     url_en: require('@/assets/videos/english/Rosa_Goes_to_the_City_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Rosa_Goes_to_the_City_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Rosa_Goes_to_the_City_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Rosa_Goes_to_the_City_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Rosa_Goes_to_the_City_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Rosa_Goes_to_the_City_Punjabi.png'),
    //     description: "This is Rosa Goes to the City ",
    //     level: "2"
    // },
    // {
    //     id: "32",
    //     english_title: "Satya, Watch Out! ",
    //     punjabi_title: "ਸੱਤਿਆ, ਧਿਆਨ ਨਾਲ!",
    //     url_en: require('@/assets/videos/english/Satya,_Watch_Out!_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Satya,_Watch_Out!_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Satya,_Watch_Out!_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Satya,_Watch_Out!_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Satya,_Watch_Out!_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Satya,_Watch_Out!_Punjabi.png'),
    //     description: "This is Satya, Watch Out! ",
    //     level: "2"
    // },
    // {
    //     id: "33",
    //     english_title: "The First Well ",
    //     punjabi_title: "ਪਹਿਲਾ ਖੂਹ",
    //     url_en: require('@/assets/videos/english/The_First_Well_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/The_First_Well_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_First_Well_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/The_First_Well_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/The_First_Well_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/The_First_Well_Punjabi.png'),
    //     description: "This is The First Well ",
    //     level: "2"
    // },
    // {
    //     id: "34",
    //     english_title: "The Flying Elephant ",
    //     punjabi_title: "ਉੱਡਣ ਵਾਲਾ ਹਾਥੀ",
    //     url_en: require('@/assets/videos/english/The_Flying_Elephant_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/The_Flying_Elephant_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Flying_Elephant_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/The_Flying_Elephant_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/The_Flying_Elephant_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/The_Flying_Elephant_Punjabi.png'),
    //     description: "This is The Flying Elephant ",
    //     level: "3"
    // },
    // {
    //     id: "35",
    //     english_title: "The Four Friends ",
    //     punjabi_title: "ਚਾਰ ਦੋਸਤ",
    //     url_en: require('@/assets/videos/english/The_Four_Friends_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/The_Four_Friends_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Four_Friends_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/The_Four_Friends_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/The_Four_Friends_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/The_Four_Friends_Punjabi.png'),
    //     description: "This is The Four Friends ",
    //     level: "3"
    // },
    // {
    //     id: "36",
    //     english_title: "The Greatest Treasure ",
    //     punjabi_title: "ਮਹਾਨ ਖਜ਼ਾਨਾ",
    //     url_en: require('@/assets/videos/english/The_Greatest_Treasure_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/The_Greatest_Treasure_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Greatest_Treasure_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/The_Greatest_Treasure_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/The_Greatest_Treasure_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/The_Greatest_Treasure_Punjabi.png'),
    //     description: "This is The Greatest Treasure ",
    //     level: "3"
    // },
    // {
    //     id: "37",
    //     english_title: "The Kings secret ",
    //     punjabi_title: "ਰਾਜੇ ਦਾ ਭੇਤ",
    //     url_en: require('@/assets/videos/english/The_Kings_secret_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/The_Kings_secret_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Kings_secret_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/The_Kings_secret_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/The_Kings_secret_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/The_Kings_secret_Punjabi.png'),
    //     description: "This is The Kings secret ",
    //     level: "3"
    // },
    // {
    //     id: "38",
    //     english_title: "The Lion and the Fox ",
    //     punjabi_title: "ਸ਼ੇਰ ਅਤੇ ਲੂੰਬੜੀ",
    //     url_en: require('@/assets/videos/english/The_Lion_and_the_Fox_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/The_Lion_and_the_Fox_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Lion_and_the_Fox_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/The_Lion_and_the_Fox_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/The_Lion_and_the_Fox_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/The_Lion_and_the_Fox_Punjabi.png'),
    //     description: "This is The Lion and the Fox ",
    //     level: "3"
    // },
    // {
    //     id: "39",
    //     english_title: "The Monks New Shawl ",
    //     punjabi_title: "ਭਿਕਸ਼ੂ ਦਾ ਨਵਾਂ ਸ਼ਾਲ",
    //     url_en: require('@/assets/videos/english/The_Monks_New_Shawl_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/The_Monks_New_Shawl_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Monks_New_Shawl_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/The_Monks_New_Shawl_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/The_Monks_New_Shawl_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/The_Monks_New_Shawl_Punjabi.png'),
    //     description: "This is The Monks New Shawl ",
    //     level: "2"
    // },
    // {
    //     id: "40",
    //     english_title: "The Moon and the Cap ",
    //     punjabi_title: "ਚੰਦਰਮਾ ਅਤੇ ਟੋਪੀ",
    //     url_en: require('@/assets/videos/english/The_Moon_and_the_Cap_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/The_Moon_and_the_Cap_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/1.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/The_Moon_and_the_Cap_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/The_Moon_and_the_Cap_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/The_Moon_and_the_Cap_Punjabi.png'),
    //     description: "This is The Moon and the Cap ",
    //     level: "1"
    // },
    // {
    //     id: "41",
    //     english_title: "The Princess Farmer ",
    //     punjabi_title: "ਕਿਸਾਨ ਰਾਜਕੁਮਾਰੀ",
    //     url_en: require('@/assets/videos/english/The_Princess_Farmer_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/The_Princess_Farmer_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/1.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/The_Princess_Farmer_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/The_Princess_Farmer_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/The_Princess_Farmer_Punjabi.png'),
    //     description: "This is The Princess Farmer ",
    //     level: "3"
    // },
    // {
    //     id: "42",
    //     english_title: "The Talktative Tortoise ",
    //     punjabi_title: "ਗਾਲ੍ਹੜੀ ਕਛੂਆ",
    //     url_en: require('@/assets/videos/english/The_Talktative_Tortoise_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/The_Talktative_Tortoise_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Talktative_Tortoise_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/The_Talktative_Tortoise_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/The_Talktative_Tortoise_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/The_Talktative_Tortoise_Punjabi.png'),
    //     description: "This is The Talktative Tortoise ",
    //     level: "2"
    // },
    // {
    //     id: "43",
    //     english_title: "The Wind and the Sun ",
    //     punjabi_title: "ਹਵਾ ਅਤੇ ਸੂਰਜ",
    //     url_en: require('@/assets/videos/english/The_Wind_and_the_Sun_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/The_Wind_and_the_Sun_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Wind_and_the_Sun_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/The_Wind_and_the_Sun_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/The_Wind_and_the_Sun_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/The_Wind_and_the_Sun_Punjabi.png'),
    //     description: "This is The Wind and the Sun ",
    //     level: "2"
    // },
    // {
    //     id: "44",
    //     english_title: "Timmy and Pepe ",
    //     punjabi_title: "ਟਿੰਮੀ ਅਤੇ ਪੇਪੇ",
    //     url_en: require('@/assets/videos/english/Timmy_and_Pepe_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Timmy_and_Pepe_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Timmy_and_Pepe_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Timmy_and_Pepe_Punjabi.pdf')),
    //     thuzmbnail_en: require('@/assets/thumbnails/english/Timmy_and_Pepe_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Timmy_and_Pepe_Punjabi.png'),
    //     description: "This is Timmy and Pepe ",
    //     level: "1"
    // },
    // {
    //     id: "45",
    //     english_title: "Too Big Too Small ",
    //     punjabi_title: "ਬਹੁਤ ਵੱਡੀ! ਬਹੁਤ ਛੋਟੀ!",
    //     url_en: require('@/assets/videos/english/Too_Big_Too_Small_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Too_Big!_Too_Small!_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/1.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Too_Big!_Too_Small!_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Too_Big!_Too_Small!_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Too_Big!_Too_Small!_Punjabi.png'),
    //     description: "This is Too Big Too Small ",
    //     level: "1"
    // },
    // {
    //     id: "46",
    //     english_title: "Too Many Bananas ",
    //     punjabi_title: "ਬਹੁਤ ਸਾਰੇ ਕੇਲੇ",
    //     url_en: require('@/assets/videos/english/Too_Many_Bananas_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Too_Many_Bananas_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Too_Many_Bananas_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Too_Many_Bananas_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Too_Many_Bananas_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Too_Many_Bananas_Punjabi.png'),
    //     description: "This is Too Many Bananas ",
    //     level: "3"
    // },
    // {
    //     id: "47",
    //     english_title: "Too Much Noise ",
    //     punjabi_title: "ਬਹੁਤ ਜ਼ਿਆਦਾ ਸ਼ੋਰ",
    //     url_en: require('@/assets/videos/english/Too_Much_Noise_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Too_Much_Noise_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Too_Much_Noise_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Too_Much_Noise_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Too_Much_Noise_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Too_Much_Noise_Punjabi.png'),
    //     description: "This is Too Much Noise ",
    //     level: "3"
    // },
    // {
    //     id: "48",
    //     english_title: "Turtles Flute ",
    //     punjabi_title: "ਕੱਛੂ ਦੀ ਬੰਸਰੀ",
    //     url_en: require('@/assets/videos/english/Turtles_Flute_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Turtles_Flute_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Turtles_Flute_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Turtles_Flute_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Turtles_Flute_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Turtles_Flute_Punjabi.png'),
    //     description: "This is Turtles Flute ",
    //     level: "2"
    // },
    // {
    //     id: "49",
    //     english_title: "Vayu, the Wind ",
    //     punjabi_title: "ਵਾਯੂ, ਹਵ",
    //     url_en: require('@/assets/videos/english/Vayu,_the_Wind_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/Vayu,_the_Wind_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Vayu,_the_Wind_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/Vayu,_the_Wind_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/Vayu,_the_Wind_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/Vayu,_the_Wind_Punjabi.png'),
    //     description: "This is Vayu, the Wind ",
    //     level: "2"
    // },
    // {
    //     id: "50",
    //     english_title: "What did you see ",
    //     punjabi_title: "ਤੁਸੀਂ ਕੀ ਵੇਖਿਆ?",
    //     url_en: require('@/assets/videos/english/What_did_you_see_English.mp4'),
    //     url_punjabi: require('@/assets/videos/punjabi/What_did_you_see_Punjabi.mp4'),
    //     pdf_en: Asset.fromModule(require('@/assets/pdfs/english/What_did_you_see_English.pdf')),
    //     pdf_punjabi: Asset.fromModule(require('@/assets/pdfs/punjabi/What_did_you_see_Punjabi.pdf')),
    //     thumbnail_en: require('@/assets/thumbnails/english/What_did_you_see_English.png'),
    //     thumbnail_punjabi: require('@/assets/thumbnails/punjabi/What_did_you_see_Punjabi.png'),
    //     description: "This is What did you see ",
    //     level: "2"
    // },
];
