import { Asset } from 'expo-asset';
// add title

export const videoDetails = [
    {
        id: "1",
        english_title: "A Cloud of Trash ",
        punjabi_title: "कचरे का बादल", 
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/A_Cloud_of_Trash_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/A_Cloud_of_Trash_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/A_Cloud_of_Trash_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/A_Cloud_of_Trash_Hindi.png'),
        description: "This is A Cloud of Trash ",
        level: "2"
    },
    {
        id: "2",
        english_title: "A Street or a Zoo ",
        punjabi_title: "गली है या चिड़ियाघर",
        //////url_en: require('@/assets/videos/english/A_Street,_or_a_Zoo_English.mp4'),
        ////url_punjabi: require('@/assets/videos/punjabi/A_Street,_or_a_Zoo_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/A_Street,_or_a_Zoo_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/A_Street,_or_a_Zoo_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/A_Street,_or_a_Zoo_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/A_Street,_or_a_Zoo_Hindi.png'),
        description: "This is A Street or a Zoo ",
        level: "2"
    },
    {
        id: "3",
        english_title: "Aaloo Maaloo Kaaloo ",
        punjabi_title: "आलू मालू कालू",
        //////url_en: require('@/assets/videos/english/Aaloo_Maaloo_Kaaloo_English.mp4'),
        ////url_punjabi: require('@/assets/videos/punjabi/Aaloo_Maaloo_Kaaloo_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Aaloo_Maaloo_Kaaloo_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Aaloo_Maaloo_Kaaloo_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Aaloo_Maaloo_Kaaloo_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Aaloo_Maaloo_Kaaloo_Hindi.png'),
        description: "This is Aaloo Maaloo Kaaloo ",
        level: "2"
    },
    {
        id: "4",
        english_title: "Abdul Kalam, A Lesson for my Teacher ",
        punjabi_title: "अब्दुल कलाम, मेरे अध्यापक के लिए एक पाठ ",
        //////url_en: require('@/assets/videos/english/Abdul_Kalam,_A_Lesson_for_my_Teacher_English.mp4'),
        ////url_punjabi: require('@/assets/videos/punjabi/Abdul_Kalam,_A_Lesson_for_my_Teacher_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Abdul_Kalam,_A_Lesson_for_my_Teacher_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Abdul_Kalam,_A_Lesson_for_my_Teacher_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Abdul_Kalam,_A_Lesson_for_my_Teacher_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Abdul_Kalam,_A_Lesson_for_my_Teacher_Hindi.png'),
        description: "This is Abdul Kalam, A Lesson for my Teacher ",
        level: "4"
    },
    {
        id: "5",
        english_title: "Abdul Kalam, Designing a Fighter Jet ",
        punjabi_title: "अब्दुल कलाम, फाइटर जैट का डिज़ाइन बनाना",
        //////url_en: require('@/assets/videos/english/Abdul_Kalam,_Designing_a_Fighter_Jet_English.mp4'),
        ////url_punjabi: require('@/assets/videos/punjabi/Abdul_Kalam,_Designing_a_Fighter_Jet_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Abdul_Kalam,_Designing_a_Fighter_Jet_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Abdul_Kalam,_Designing_a_Fighter_Jet_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Abdul_Kalam,_Designing_a_Fighter_Jet_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Abdul_Kalam,_Designing_a_Fighter_Jet_Hindi.png'),
        description: "This is Abdul Kalam, Designing a Fighter Jet ",
        level: "4"
    },
    {
        id: "6",
        english_title: "Abdul Kalam, Failure to Success ",
        punjabi_title: "अब्दुल कलाम, असफ़लता से सफ़लता की ओर",
        //////url_en: require('@/assets/videos/english/Abdul_Kalam,_Failure_to_Success_English.mp4'),
        ////url_punjabi: require('@/assets/videos/punjabi/Abdul_Kalam,_Failure_to_Success_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Abdul_Kalam,_Failure_to_Success_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Abdul_Kalam,_Failure_to_Success_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Abdul_Kalam,_Failure_to_Success_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Abdul_Kalam,_Failure_to_Success_Hindi.png'),
        description: "This is Abdul Kalam, Failure to Success ",
        level: "4"
    },
    {
        id: "7",
        english_title: "Abdul Kalam, Missile Man ",
        punjabi_title: "अब्दुल कलाम, मिसाइल मैन",
        //////url_en: require('@/assets/videos/english/Abdul_Kalam,_Missile_Man_English.mp4'),
        ////url_punjabi: require('@/assets/videos/punjabi/Abdul_Kalam,_Missile_Man_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Abdul_Kalam,_Missile_Man_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Abdul_Kalam,_Missile_Man_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Abdul_Kalam,_Missile_Man_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Abdul_Kalam,_Missile_Man_Hindi.png'),
        description: "This is Abdul Kalam, Missile Man ",
        level: "4"
    },
    {
        id: "8",
        english_title: "Abdul Kalam, School Topper ",
        punjabi_title: "अब्दुल कलाम, मैं प्रथम आया",
        //////url_en: require('@/assets/videos/english/Abdul_Kalam,_School_Topper_English.mp4'),
        ////url_punjabi: require('@/assets/videos/punjabi/Abdul_Kalam,_School_Topper_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Abdul_Kalam,_School_Topper_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Abdul_Kalam,_School_Topper_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Abdul_Kalam,_School_Topper_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Abdul_Kalam,_School_Topper_Hindi.png'),
        description: "This is Abdul Kalam, School Topper ",
        level: "4"
    },
    {
        id: "9",
        english_title: "Ammus Puppy ",
        punjabi_title: "अम्मू का कुत्ता",
        //////url_en: require('@/assets/videos/english/Ammus_Puppy_English.mp4'),
        ////url_punjabi: require('@/assets/videos/punjabi/Ammus_Puppy_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Ammus_Puppy_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Ammus_Puppy_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Ammus_Puppy_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Ammus_Puppy_Hindi.png'),
        description: "This is Ammus Puppy ",
        level: "3"
    },
    {
        id: "10",
        english_title: "Bheema, the Sleepyhead ",
        punjabi_title: "भीमा गधा",
        //////url_en: require('@/assets/videos/english/Bheema,_the_Sleepyhead_English.mp4'),
        ////url_punjabi: require('@/assets/videos/punjabi/Bheema,_the_Sleepyhead_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Bheema,_the_Sleepyhead_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Bheema,_the_Sleepyhead_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Bheema,_the_Sleepyhead_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Bheema,_the_Sleepyhead_Hindi.png'),
        description: "This is Bheema, the Sleepyhead ",
        level: "3"
    },
    {
        id: "11",
        english_title: "Bunty and Bubbly ",
        punjabi_title: "बंटी और बबली",
        //////url_en: require('@/assets/videos/english/Bunty_and_Bubbly_English.mp4'),
        ////url_punjabi: require('@/assets/videos/punjabi/Bunty_and_Bubbly_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Bunty_and_Bubbly_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Bunty_and_Bubbly_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Bunty_and_Bubbly_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Bunty_and_Bubbly_Hindi.png'),
        description: "This is Bunty and Bubbly ",
        level: "1"
    },
    {
        id: "12",
        english_title: "Cheeku & Chikootichoo ",
        punjabi_title: "चीकू और चिकूटिचू",
        //////url_en: require('@/assets/videos/english/Cheeku_&_Chikootichoo_English.mp4'),
        ////url_punjabi: require('@/assets/videos/punjabi/Cheeku_&_Chikootichoo_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Cheeku_&_Chikootichoo_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Cheeku_&_Chikootichoo_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Cheeku_&_Chikootichoo_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Cheeku_&_Chikootichoo_Hindi.png'),
        description: "This is Cheeku & Chikootichoo ",
        level: "2"
    },
    {
        id: "13",
        english_title: "Cheeku & Lizzy Bizzy ",
        punjabi_title: "चीकू और लिज़्ज़ी बिज़्ज़ी",
        ////url_en: require('@/assets/videos/english/Cheeku_&_Lizzy_Bizzy_English.mp4'),
        ////url_punjabi: require('@/assets/videos/punjabi/Cheeku_&_Lizzy_Bizzy_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Cheeku_&_Lizzy_Bizzy_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Cheeku_&_Lizzy_Bizzy_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Cheeku_&_Lizzy_Bizzy_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Cheeku_&_Lizzy_Bizzy_Hindi.png'),
        description: "This is Cheeku & Lizzy Bizzy ",
        level: "2"
    },
    {
        id: "14",
        english_title: "Cheeku & Tooi ",
        punjabi_title: "चीकू और तूई",
        ////url_en: require('@/assets/videos/english/Cheeku_&_Tooi_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Cheeku_&_Tooi_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Cheeku_&_Tooi_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Cheeku_&_Tooi_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Cheeku_&_Tooi_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Cheeku_&_Tooi_Hindi.png'),
        description: "This is Cheeku & Tooi ",
        level: "2"
    },
    {
        id: "15",
        english_title: "Cricket at the Zoo ",
        punjabi_title: "चिड़ियाघर में क्रिकेट",
        ////url_en: require('@/assets/videos/english/Cricket_at_the_Zoo_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Cricket_at_the_Zoo_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Cricket_at_the_Zoo_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Cricket_at_the_Zoo_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Cricket_at_the_Zoo_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Cricket_at_the_Zoo_Hindi.png'),
        description: "This is Cricket at the Zoo ",
        level: "3"
    },
    {
        id: "16",
        english_title: "Didi and the Colourful Treasure ",
        punjabi_title: "दीदी और उनका रंग-बिरंगा खज़ाना",
        ////url_en: require('@/assets/videos/english/Didi_and_the_Colourful_Treasure_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Didi_and_the_Colourful_Treasure_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Didi_and_the_Colourful_Treasure_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Didi_and_the_Colourful_Treasure_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Didi_and_the_Colourful_Treasure_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Didi_and_the_Colourful_Treasure_Hindi.png'),
        description: "This is Didi and the Colourful Treasure ",
        level: "2"
    },
    {
        id: "17",
        english_title: "Farida Plans a Feast ",
        punjabi_title: "फरीदा की दावत",
        ////url_en: require('@/assets/videos/english/Farida_Plans_a_Feast_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Farida_Plans_a_Feast_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Farida_Plans_a_Feast_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Farida_Plans_a_Feast_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Farida_Plans_a_Feast_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Farida_Plans_a_Feast_Hindi.png'),
        description: "This is Farida Plans a Feast ",
        level: "2"
    },
    {
        id: "18",
        english_title: "Gajapati Kulapati ",
        punjabi_title: "गजपति कुलपति",
        ////url_en: require('@/assets/videos/english/Gajapati_Kulapati_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Gajapati_Kulapati_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Gajapati_Kulapati_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Gajapati_Kulapati_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Gajapati_Kulapati_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Gajapati_Kulapati_Hindi.png'),
        description: "This is Gajapati Kulapati ",
        level: "3"
    },
    {
        id: "19",
        english_title: "Kiran Bedi, Crane Bedi ",
        punjabi_title: "किरण बेदी, क्रेन बेदी",
        ////url_en: require('@/assets/videos/english/Kiran_Bedi,_Crane_Bedi_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Kiran_Bedi,_Crane_Bedi_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Kiran_Bedi,_Crane_Bedi_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Kiran_Bedi,_Crane_Bedi_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Kiran_Bedi,_Crane_Bedi_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Kiran_Bedi,_Crane_Bedi_Hindi.png'),
        description: "This is Kiran Bedi, Crane Bedi ",
        level: "4"
    },
    {
        id: "20",
        english_title: "Kiran Bedi, How to Lose a Shoe ",
        punjabi_title: "किरण बेदी, अगर एक जूता खो जाये",
        ////url_en: require('@/assets/videos/english/Kiran_Bedi,_How_to_Lose_a_Shoe_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Kiran_Bedi,_How_to_Lose_a_Shoe_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Kiran_Bedi,_How_to_Lose_a_Shoe_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Kiran_Bedi,_How_to_Lose_a_Shoe_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Kiran_Bedi,_How_to_Lose_a_Shoe_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Kiran_Bedi,_How_to_Lose_a_Shoe_Hindi.png'),
        description: "This is Kiran Bedi, How to Lose a Shoe ",
        level: "4"
    },
    {
        id: "21",
        english_title: "Kiran Bedi, Thank you Mr. Secretary ",
        punjabi_title: "किरण बेदी, शुक्रिया सेक्रेटरी साहब",
        ////url_en: require('@/assets/videos/english/Kiran_Bedi,_Thank_you_Mr._Secretary_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Kiran_Bedi,_Thank_you_Mr._Secretary_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Kiran_Bedi,_Thank_you_Mr._Secretary_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Kiran_Bedi,_Thank_you_Mr._Secretary_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Kiran_Bedi,_Thank_you_Mr._Secretary_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Kiran_Bedi,_Thank_you_Mr._Secretary_Hindi.png'),
        description: "This is Kiran Bedi, Thank you Mr. Secretary ",
        level: "4"
    },
    {
        id: "22",
        english_title: "Kiran Bedi, Tihar Jail ",
        punjabi_title: "किरण बेदी, तिहाड़ जेल",
        ////url_en: require('@/assets/videos/english/Kiran_Bedi,_Tihar_Jail_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Kiran_Bedi,_Tihar_Jail_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Kiran_Bedi,_Tihar_Jail_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Kiran_Bedi,_Tihar_Jail_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Kiran_Bedi,_Tihar_Jail_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Kiran_Bedi,_Tihar_Jail_Hindi.png'),
        description: "This is Kiran Bedi, Tihar Jail ",
        level: "4"
    },
    {
        id: "23",
        english_title: "Lost and Found ",
        punjabi_title: "खोया पाया",
        ////url_en: require('@/assets/videos/english/Lost_and_Found_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Lost_and_Found_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Lost_and_Found_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Lost_and_Found_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Lost_and_Found_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Lost_and_Found_Hindi.png'),
        description: "This is Lost and Found ",
        level: "2"
    },
    {
        id: "24",
        english_title: "Mahatma Gandhi, The Salt March ",
        punjabi_title: "महात्मा गांधी, नमक सत्याग्रह",
        ////url_en: require('@/assets/videos/english/Mahatma_Gandhi,_The_Salt_March_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Mahatma_Gandhi,_The_Salt_March_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Mahatma_Gandhi,_The_Salt_March_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Mahatma_Gandhi,_The_Salt_March_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Mahatma_Gandhi,_The_Salt_March_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Mahatma_Gandhi,_The_Salt_March_Hindi.png'),
        description: "This is Mahatma Gandhi, The Salt March ",
        level: "4"
    },
    {
        id: "25",
        english_title: "My Car ",
        punjabi_title: "मेरी कार",
        ////url_en: require('@/assets/videos/english/My_Car_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/My_Car_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Cheeku_&_Whoop_Ha_Ha_English.pdf')), ///this issue
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/My_Car_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/My_Car_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/My_Car_Hindi.png'),
        description: "This is My Car ",
        level: "2"
    },
    {
        id: "26",
        english_title: "No Smiles Today ",
        punjabi_title: "हँसना मना है",
        ////url_en: require('@/assets/videos/english/No_Smiles_Today_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/No_Smiles_Today_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/No_Smiles_Today_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/No_Smiles_Today_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/No_Smiles_Today_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/No_Smiles_Today_Hindi.png'),
        description: "This is No Smiles Today ",
        level: "3"
    },
    {
        id: "27",
        english_title: "Pishi Caught in a Storm ",
        punjabi_title: "पिशि फँसी तूफ़ान में",
        ////url_en: require('@/assets/videos/english/Pishi_Caught_in_a_Storm_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Pishi_Caught_in_a_Storm_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Pishi_Caught_in_a_Storm_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Pishi_Caught_in_a_Storm_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Pishi_Caught_in_a_Storm_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Pishi_Caught_in_a_Storm_Hindi.png'),
        description: "This is Pishi Caught in a Storm ",
        level: "3"
    },
    {
        id: "28",
        english_title: "Punyakoti the Cow ",
        punjabi_title: "पुण्यकोटि गाय",
        ////url_en: require('@/assets/videos/english/Punyakoti_the_Cow_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Punyakoti_the_Cow_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Punyakoti,_the_Cow_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Punyakoti,_the_Cow_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Punyakoti,_the_Cow_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Punyakoti,_the_Cow_Hindi.png'),
        description: "This is Punyakoti the Cow ",
        level: "4"
    },
    {
        id: "29",
        english_title: "Rain Rain ",
        punjabi_title: "बरसा बादल",
        ////url_en: require('@/assets/videos/english/Rain_Rain_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Rain_Rain_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Cheeku_&_Oonderbhai_English.pdf')), // issue
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Rain_Rain_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Rain_Rain_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Rain_Rain_Hindi.png'),
        description: "This is Rain Rain ",
        level: "2"
    },
    {
        id: "30",
        english_title: "Ranis First Day at School ",
        punjabi_title: "स्कूल का पहला दिन",
        ////url_en: require('@/assets/videos/english/Ranis_First_Day_at_School_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Ranis_First_Day_at_School_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Ranis_First_Day_at_School_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Ranis_First_Day_at_School_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Ranis_First_Day_at_School_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Ranis_First_Day_at_School_Hindi.png'),
        description: "This is Ranis First Day at School ",
        level: "2"
    },
    {
        id: "31",
        english_title: "Rosa Goes to the City ",
        punjabi_title: "हाथी शहर को गया",
        ////url_en: require('@/assets/videos/english/Rosa_Goes_to_the_City_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Rosa_Goes_to_the_City_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Rosa_Goes_to_the_City_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Rosa_Goes_to_the_City_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Rosa_Goes_to_the_City_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Rosa_Goes_to_the_City_Hindi.png'),
        description: "This is Rosa Goes to the City ",
        level: "2"
    },
    {
        id: "32",
        english_title: "Satya, Watch Out! ",
        punjabi_title: "सत्या, ज़रा संभल के!",
        ////url_en: require('@/assets/videos/english/Satya,_Watch_Out!_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Satya,_Watch_Out!_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Satya,_Watch_Out!_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Satya,_Watch_Out!_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Satya,_Watch_Out!_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Satya,_Watch_Out!_Hindi.png'),
        description: "This is Satya, Watch Out! ",
        level: "2"
    },
    {
        id: "33",
        english_title: "The First Well ",
        punjabi_title: "पहला कुआँ",
        ////url_en: require('@/assets/videos/english/The_First_Well_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/The_First_Well_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_First_Well_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/The_First_Well_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/The_First_Well_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/The_First_Well_Hindi.png'),
        description: "This is The First Well ",
        level: "2"
    },
    {
        id: "34",
        english_title: "The Flying Elephant ",
        punjabi_title: "उड़नहाथी",
        ////url_en: require('@/assets/videos/english/The_Flying_Elephant_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/The_Flying_Elephant_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Flying_Elephant_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/The_Flying_Elephant_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/The_Flying_Elephant_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/The_Flying_Elephant_Hindi.png'),
        description: "This is The Flying Elephant ",
        level: "3"
    },
    {
        id: "35",
        english_title: "The Four Friends ",
        punjabi_title: "चार मित्र",
        ////url_en: require('@/assets/videos/english/The_Four_Friends_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/The_Four_Friends_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Four_Friends_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/The_Four_Friends_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/The_Four_Friends_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/The_Four_Friends_Hindi.png'),
        description: "This is The Four Friends ",
        level: "3"
    },
    {
        id: "36",
        english_title: "The Greatest Treasure ",
        punjabi_title: "सबसे बड़ा खज़ाना",
        ////url_en: require('@/assets/videos/english/The_Greatest_Treasure_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/The_Greatest_Treasure_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Greatest_Treasure_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/The_Greatest_Treasure_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/The_Greatest_Treasure_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/The_Greatest_Treasure_Hindi.png'),
        description: "This is The Greatest Treasure ",
        level: "3"
    },
    {
        id: "37",
        english_title: "The Kings Secret ",
        punjabi_title: "राजा का राज़",
        ////url_en: require('@/assets/videos/english/The_Kings_secret_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/The_Kings_secret_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Kings_secret_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/The_Kings_secret_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/The_Kings_secret_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/The_Kings_secret_Hindi.png'),
        description: "This is The Kings secret ",
        level: "3"
    },
    {
        id: "38",
        english_title: "The Lion and the Fox ",
        punjabi_title: "शेर और लोमड़ी",
        ////url_en: require('@/assets/videos/english/The_Lion_and_the_Fox_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/The_Lion_and_the_Fox_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Lion_and_the_Fox_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/The_Lion_and_the_Fox_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/The_Lion_and_the_Fox_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/The_Lion_and_the_Fox_Hindi.png'),
        description: "This is The Lion and the Fox ",
        level: "3"
    },
    {
        id: "39",
        english_title: "The Monks New Shawl ",
        punjabi_title: "भिक्षु का नया शॉल",
        ////url_en: require('@/assets/videos/english/The_Monks_New_Shawl_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/The_Monks_New_Shawl_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Monks_New_Shawl_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/The_Monks_New_Shawl_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/The_Monks_New_Shawl_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/The_Monks_New_Shawl_Hindi.png'),
        description: "This is The Monks New Shawl ",
        level: "2"
    },
    {
        id: "40",
        english_title: "The Moon and the Cap ",
        punjabi_title: "चंदा और टोपी",
        ////url_en: require('@/assets/videos/english/The_Moon_and_the_Cap_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/The_Moon_and_the_Cap_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Moon_and_the_Cap_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/The_Moon_and_the_Cap_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/The_Moon_and_the_Cap_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/The_Moon_and_the_Cap_Hindi.png'),
        description: "This is The Moon and the Cap ",
        level: "1"
    },
    {
        id: "41",
        english_title: "The Princess Farmer ",
        punjabi_title: "किसान राजकुमारी",
        ////url_en: require('@/assets/videos/english/The_Princess_Farmer_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/The_Princess_Farmer_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Princess_Farmer_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/The_Princess_Farmer_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/The_Princess_Farmer_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/The_Princess_Farmer_Hindi.png'),
        description: "This is The Princess Farmer ",
        level: "3"
    },
    {
        id: "42",
        english_title: "The Talkative Tortoise ",
        punjabi_title: "बातूनी कछुआ",
        ////url_en: require('@/assets/videos/english/The_Talktative_Tortoise_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/The_Talktative_Tortoise_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/The_Talktative_Tortoise_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/The_Talktative_Tortoise_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/The_Talktative_Tortoise_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/The_Talktative_Tortoise_Hindi.png'),
        description: "This is The Talktative Tortoise ",
        level: "2"
    },
    {
        id: "43",
        english_title: "The Wind and the Sun ",
        punjabi_title: "हवा और सूरज",
        ////url_en: require('@/assets/videos/english/The_Wind_and_the_Sun_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/The_Wind_and_the_Sun_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/hindi/The_Wind_and_the_Sun_Hindi.pdf')), // issue
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/The_Wind_and_the_Sun_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/The_Wind_and_the_Sun_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/The_Wind_and_the_Sun_Hindi.png'),
        description: "This is The Wind and the Sun ",
        level: "2"
    },
    {
        id: "44",
        english_title: "Timmy and Pepe ",
        punjabi_title: "टिमी और पेपे",
        ////url_en: require('@/assets/videos/english/Timmy_and_Pepe_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Timmy_and_Pepe_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Timmy_and_Pepe_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Timmy_and_Pepe_Hindi.pdf')),
        thuzmbnail_en: require('@/assets/thumbnails/english/Timmy_and_Pepe_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Timmy_and_Pepe_Hindi.png'),
        description: "This is Timmy and Pepe ",
        level: "1"
    },
    {
        id: "45",
        english_title: "Too Big Too Small ",
        punjabi_title: "बहुत बड़ी! बहुत छोटी!",
        ////url_en: require('@/assets/videos/english/Too_Big_Too_Small_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Too_Big!_Too_Small!_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Too_Big!_Too_Small!_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Too_Big!_Too_Small!_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Too_Big!_Too_Small!_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Too_Big!_Too_Small!_Hindi.png'),
        description: "This is Too Big Too Small ",
        level: "1"
    },
    {
        id: "46",
        english_title: "Too Many Bananas ",
        punjabi_title: "केले के गुच्छे",
        ////url_en: require('@/assets/videos/english/Too_Many_Bananas_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Too_Many_Bananas_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Too_Many_Bananas_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Too_Many_Bananas_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Too_Many_Bananas_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Too_Many_Bananas_Hindi.png'),
        description: "This is Too Many Bananas ",
        level: "3"
    },
    {
        id: "47",
        english_title: "Too Much Noise ",
        punjabi_title: "इतना सारा शोर शराबा",
        ////url_en: require('@/assets/videos/english/Too_Much_Noise_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Too_Much_Noise_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Too_Much_Noise_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Too_Much_Noise_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Too_Much_Noise_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Too_Much_Noise_Hindi.png'),
        description: "This is Too Much Noise ",
        level: "3"
    },
    {
        id: "48",
        english_title: "Turtles Flute ",
        punjabi_title: "कछुए की बांसुरी",
        ////url_en: require('@/assets/videos/english/Turtles_Flute_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Turtles_Flute_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Turtles_Flute_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Turtles_Flute_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Turtles_Flute_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Turtles_Flute_Hindi.png'),
        description: "This is Turtles Flute ",
        level: "2"
    },
    {
        id: "49",
        english_title: "Vayu, the Wind ",
        punjabi_title: "वायु ̶ ­­­­यह है हवा!",
        ////url_en: require('@/assets/videos/english/Vayu,_the_Wind_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/Vayu,_the_Wind_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/Vayu,_the_Wind_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/Vayu,_the_Wind_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/Vayu,_the_Wind_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/Vayu,_the_Wind_Hindi.png'),
        description: "This is Vayu, the Wind ",
        level: "2"
    },
    {
        id: "50",
        english_title: "What did you see ",
        punjabi_title: "तुमने क्या देखा?",
        ////url_en: require('@/assets/videos/english/What_did_you_see_English.mp4'),
        //url_punjabi: require('@/assets/videos/punjabi/What_did_you_see_Punjabi.mp4'),
        pdf_en: Asset.fromModule(require('@/assets/pdfs/english/What_did_you_see_English.pdf')),
        pdf_hindi: Asset.fromModule(require('@/assets/pdfs/hindi/What_did_you_see_Hindi.pdf')),
        thumbnail_en: require('@/assets/thumbnails/english/What_did_you_see_English.png'),
        thumbnail_hindi: require('@/assets/thumbnails/hindi/What_did_you_see_Hindi.png'),
        description: "This is What did you see ",
        level: "2"
    },
];
